apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-nginx
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gateway-nginx
  template:
    metadata:
      labels:
        app: gateway-nginx
    spec:
      containers:
      - image: nginx:1.23.2-alpine
        name: gateway-nginx
        ports:
        - containerPort: 80
