apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-nginx
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gateway-nginx
  template:
    metadata:
      labels:
        app: gateway-nginx
    spec:
      containers:
      - image: nginx:latest
        name: gateway-nginx
        ports:
        - containerPort: 80
